workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - build


job1:
  stage: build
  script:
    - echo "This job runs in the build stage."
    - npm install
    - npm run-script build
    - ls
    
    - rm -rf /var/www/html/dist
    - mv dist /var/www/html/
