#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG
server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: http://124.221.102.208:8085 # nacos 地址
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 15000
      routes:
        - id: SentiStrength # SentiStrength 路由标识
          uri: http://124.221.102.208:8081 # 路由的目标地址
          order: 1
          predicates:
            - Path=/senti-strength/**
        - id: controller # Controller 路由标识
          uri: http://124.221.102.208:8082 # 路由的目标地址
          order: 1
          predicates:
            - Path=/controller/**
        - id: nacos # nacos 路由标识
          uri: http://124.221.102.208:8085 # 路由的目标地址
          order: 1
          predicates:
            - Path=/nacos/**


