workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - build
  - test
  - deploy
  - release

job1:
  stage: build
  script:
    - echo "This job compiles code."
    - mvn compile
    - mvn package

job2:
  stage: test
  script:
    - echo "This job tests the compiled code. It runs when the build stage completes."
    - mvn test

job3:
  script:
    - echo "This job also runs in the test stage".

job4:
  stage: deploy
  script:
    - echo "This job deploys the code. It runs when the test stage completes."

job5:
  stage: release
  script:
    - echo "asd".
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true
  release:
    tag_name: v0.$CI_PIPELINE_IID
    description: '$CI_PIPELINE_IID'
    assets:
      links:
        - name: 'jarRelease'
          url: 'http://124.221.102.208:8092/'

  environment: production